name: Deployment pipeline

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches: [master]
    types: [opened, synchronize]
  workflow_dispatch:


jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - name: commit messages
        env:
          COMMITS: ${{join(github.event.commits.*.message)}}
        run: echo "$COMMITS"
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: E2E Test
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Deploy
        id: deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        if: (github.event_name == 'push') && !(contains(join(github.event.commits.*.message), '#skip'))
      - name: Rollback
        run: flyctl deploy -i `flyctl releases -j | jq ".[1].ImageRef" -r` --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        if: failure() && (steps.deploy.outcome == 'failure')
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.66.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
        if: (github.event_name == 'push') && !(contains(join(github.event.commits.*.message), '#skip'))
