name: Rollback

on: workflow_dispatch

jobs:
  rollback:
    runs-on: ubuntu-20.04
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Rollback
        run: flyctl deploy -i `flyctl releases -j | jq ".[1].ImageRef" -r`
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}